name: Scryfall Spoiler Bot

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Run bot
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: node spoilers.js

      - name: Commit updated state
        run: |
          git config user.name "spoiler-bot"
          git config user.email "spoiler-bot@users.noreply.github.com"

          git add seen.json

          git diff --staged --quiet || git commit -m "Update seen spoilers"

          git push
